"""receipts

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-03 03:16:13.121530
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "receipts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("message_id", sa.String(length=300), nullable=False),
        sa.Column("mail_subject", sa.String(length=500), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("pdf_file", sa.String(length=200), nullable=True),
        sa.Column("pdf_name", sa.String(length=200), nullable=False),
        sa.Column("station", sa.String(length=200), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("paid_at", sa.DateTime(), nullable=True),
        sa.Column("printed_date", sa.String(length=100), nullable=True),
        sa.Column("fuel_type", sa.String(length=100), nullable=True),
        sa.Column("quantity", sa.String(), nullable=True),
        sa.Column("unit", sa.String(length=20), nullable=True),
        sa.Column("total", sa.String(), nullable=True),
        sa.Column("currency", sa.String(length=10), nullable=True),
        sa.Column("transaction_id", sa.String(length=100), nullable=True),
        sa.Column("missing", sa.JSON(), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("parse_error", sa.Text(), nullable=True),
        sa.Column("notified", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_receipts")),
        sa.UniqueConstraint("message_id", name=op.f("uq_receipts_message_id")),
    )
    with op.batch_alter_table("receipts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_receipts_paid_at"), ["paid_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_receipts_state"), ["state"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_receipts_transaction_id"), ["transaction_id"], unique=False
        )

    with op.batch_alter_table("fuel_ups", schema=None) as batch_op:
        batch_op.add_column(sa.Column("lubelogger_file", sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column("receipt_id", sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f("ix_fuel_ups_receipt_id"), ["receipt_id"], unique=False)
        batch_op.create_foreign_key(
            batch_op.f("fk_fuel_ups_receipt_id_receipts"),
            "receipts",
            ["receipt_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fuel_ups", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_fuel_ups_receipt_id_receipts"), type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_fuel_ups_receipt_id"))
        batch_op.drop_column("receipt_id")
        batch_op.drop_column("lubelogger_file")

    with op.batch_alter_table("receipts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_receipts_transaction_id"))
        batch_op.drop_index(batch_op.f("ix_receipts_state"))
        batch_op.drop_index(batch_op.f("ix_receipts_paid_at"))

    op.drop_table("receipts")
    # ### end Alembic commands ###
