"""fuel ups notifications settings

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-03 03:04:07.180886
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "settings_overrides",
        sa.Column("key", sa.String(length=50), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "fuel_ups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("created_by_name", sa.String(length=50), nullable=False),
        sa.Column("vehicle_id", sa.Integer(), nullable=False),
        sa.Column("vehicle_name", sa.String(length=200), nullable=False),
        sa.Column("odometer", sa.Integer(), nullable=False),
        sa.Column("fuel_up_time", sa.DateTime(), nullable=False),
        sa.Column("is_fill_to_full", sa.Boolean(), nullable=False),
        sa.Column("missed_fuel_up", sa.Boolean(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("payment_source", sa.String(length=20), nullable=False),
        sa.Column("fuel_type", sa.String(length=100), nullable=True),
        sa.Column("quantity", sa.String(), nullable=True),
        sa.Column("total_price", sa.String(), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("attention", sa.String(length=30), nullable=True),
        sa.Column("attention_message", sa.Text(), nullable=True),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("pending_since", sa.DateTime(), nullable=True),
        sa.Column("send_attempts", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(), nullable=True),
        sa.Column("lubelogger_record_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("fuel_ups", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_fuel_ups_created_by_id"), ["created_by_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_fuel_ups_next_attempt_at"), ["next_attempt_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_fuel_ups_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_fuel_ups_vehicle_id"), ["vehicle_id"], unique=False)

    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("level", sa.String(length=10), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("fuel_up_id", sa.Integer(), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_notifications_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notifications_user_id"))

    op.drop_table("notifications")
    with op.batch_alter_table("fuel_ups", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fuel_ups_vehicle_id"))
        batch_op.drop_index(batch_op.f("ix_fuel_ups_status"))
        batch_op.drop_index(batch_op.f("ix_fuel_ups_next_attempt_at"))
        batch_op.drop_index(batch_op.f("ix_fuel_ups_created_by_id"))

    op.drop_table("fuel_ups")
    op.drop_table("settings_overrides")
    # ### end Alembic commands ###
